name: Thomas Patrick Levy
favicon: null
layout_spectrum: 0.39762
typography_spectrum: 0.56267
title: Thomas Patrick Levy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191919'
    - '#d9d5c7'
    - '#abaca3'
    - '#4e504f'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
